"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var attach_1 = require("./attach");
exports.attach = attach_1.command;
var changeContext_1 = require("./changeContext");
exports.changeContext = changeContext_1.command;
var new_1 = require("./new");
exports.create = new_1.command;
var getAttribute_1 = require("./getAttribute");
exports.getAttribute = getAttribute_1.command;
var list_1 = require("./list");
exports.list = list_1.command;
var login_1 = require("./login");
exports.login = login_1.command;
var lookup_1 = require("./lookup");
exports.lookup = lookup_1.command;
var printCurrentContext_1 = require("./printCurrentContext");
exports.printCurrentContext = printCurrentContext_1.command;
var region_1 = require("./region");
exports.setRegion = region_1.setRegionCmd;
exports.getRegion = region_1.getRegionCmd;
exports.popRegion = region_1.popRegionCmd;
exports.getRegionCenter = region_1.getCenterCmd;
exports.printRegion = region_1.printRegionCmd;
exports.bufferRegion = region_1.bufferRegionCmd;
var setAttribute_1 = require("./setAttribute");
exports.setAttribute = setAttribute_1.command;
